# Generated by Django 2.1.1 on 2020-02-24 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='lessons',
            field=models.IntegerField(default=0, verbose_name='总课时数量'),
        ),
    ]
