# Generated by Django 2.1.1 on 2020-02-24 18:52

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_course_lessons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='brief',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=200, null=True, verbose_name='简介'),
        ),
    ]
